import { Link } from 'react-router-dom'
import BrandMark from '../components/BrandMark'

const EFFECTIVE = 'July 14, 2026'
const CONTACT = 'support@rocmporter.app'

function LegalShell({ title, children }) {
  return (
    <div className="legal-page">
      <div className="ambient-bg" aria-hidden="true"></div>
      <div className="ambient-grid" aria-hidden="true"></div>
      <header className="legal-header">
        <Link to="/" className="auth-brand">
          <BrandMark size={26} />
          <span>ROCmPorter</span>
        </Link>
      </header>
      <main className="legal-content">
        <h1>{title}</h1>
        <p className="legal-meta">Effective {EFFECTIVE}</p>
        {children}
        <p className="legal-footer-links">
          <Link to="/terms">Terms</Link> · <Link to="/privacy">Privacy</Link> · <Link to="/">Home</Link>
        </p>
      </main>
    </div>
  )
}

export function Terms() {
  return (
    <LegalShell title="Terms of Service">
      <p>
        These Terms govern your use of ROCmPorter (the “Service”), which scans public and private GitHub
        repositories for CUDA/NVIDIA dependencies and generates AMD ROCm migration guidance and patches. By
        creating an account or using the Service, you agree to these Terms.
      </p>
      <h2>1. Accounts</h2>
      <p>
        You sign in with GitHub or Google. You are responsible for activity under your account and for the
        repositories you choose to scan. You must have the right to scan any repository you submit.
      </p>
      <h2>2. Plans &amp; billing</h2>
      <p>
        Public repository scanning is free. Paid plans (billed via Stripe) unlock AI patch generation,
        verified apply, and review automation. Subscriptions renew automatically until cancelled. You can
        cancel at any time; access continues until the end of the paid period. Fees are non-refundable except
        where required by law.
      </p>
      <h2>3. Acceptable use</h2>
      <p>
        Do not use the Service to violate any law, infringe intellectual property, scan repositories you are
        not authorized to access, or attempt to disrupt or reverse-engineer the Service.
      </p>
      <h2>4. AI-generated output</h2>
      <p>
        Migration patches are generated by automated models and are provided “as is” for your review. You are
        responsible for reviewing, testing, and validating any generated code before use. We do not guarantee
        correctness, and we are not liable for outcomes of applying generated changes.
      </p>
      <h2>5. Warranty &amp; liability</h2>
      <p>
        The Service is provided “as is” without warranties of any kind. To the maximum extent permitted by
        law, our aggregate liability is limited to the amount you paid in the prior three months.
      </p>
      <h2>6. Changes &amp; termination</h2>
      <p>
        We may update these Terms or the Service. We may suspend accounts that violate these Terms. You may
        stop using the Service at any time.
      </p>
      <h2>7. Contact</h2>
      <p>
        Questions: <a href={`mailto:${CONTACT}`}>{CONTACT}</a>.
      </p>
      <p className="legal-note">
        This is a general template and not legal advice. Have a lawyer review it for your jurisdiction before
        launch.
      </p>
    </LegalShell>
  )
}

export function Privacy() {
  return (
    <LegalShell title="Privacy Policy">
      <p>
        This policy explains what data ROCmPorter collects, why, and who processes it.
      </p>
      <h2>1. Data we collect</h2>
      <ul>
        <li><strong>Account:</strong> your email and profile basics from GitHub or Google when you sign in.</li>
        <li><strong>Repository access:</strong> when you connect GitHub, we use your authorization to read the repositories you choose to scan. We do not store your source code beyond what is needed to produce a scan result.</li>
        <li><strong>Scan history:</strong> repository name, portability score, risk level, and finding counts.</li>
        <li><strong>Billing:</strong> your plan and a Stripe customer identifier. Card details are handled entirely by Stripe — we never see or store them.</li>
      </ul>
      <h2>2. How we use it</h2>
      <p>To provide scans and patches, manage your subscription, and operate and secure the Service.</p>
      <h2>3. Processors we rely on</h2>
      <ul>
        <li><strong>Supabase</strong> — authentication and database.</li>
        <li><strong>Stripe</strong> — payment processing.</li>
        <li><strong>Render</strong> — backend hosting and repository scanning.</li>
        <li><strong>Vercel</strong> — frontend hosting.</li>
        <li><strong>An LLM provider</strong> (e.g. Groq/OpenAI) — generating patch suggestions from the relevant file contents.</li>
      </ul>
      <h2>4. Data retention &amp; your rights</h2>
      <p>
        We keep account and scan-history data until you delete your account. You may request access to, or
        deletion of, your data by emailing <a href={`mailto:${CONTACT}`}>{CONTACT}</a>.
      </p>
      <h2>5. Security</h2>
      <p>
        We use encrypted connections and scoped credentials. No system is perfectly secure; use the Service at
        your own discretion.
      </p>
      <h2>6. Contact</h2>
      <p><a href={`mailto:${CONTACT}`}>{CONTACT}</a></p>
      <p className="legal-note">
        This is a general template and not legal advice. Have a lawyer review it for your jurisdiction and
        applicable regulations (e.g. GDPR) before launch.
      </p>
    </LegalShell>
  )
}
